# Generated by Django 4.2.7 on 2024-02-12 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("llm_chat", "0003_chatmessage_cost_chatmessage_tokens_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HugChatMessage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.CharField(max_length=512)),
                ("answer", models.CharField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="power_messages",
                        to="llm_chat.customprofile",
                    ),
                ),
            ],
        ),
    ]
