# Generated by Django 4.2.7 on 2024-02-12 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("llm_chat", "0003_chatmessage_cost_chatmessage_tokens_and_more"),
        ("hug_chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hugchatmessage",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="power_messages",
                to="llm_chat.userdata",
            ),
        ),
    ]
