# Generated by Django 4.2.7 on 2024-02-12 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hug_chat", "0002_alter_hugchatmessage_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hugchatmessage",
            old_name="question",
            new_name="message",
        ),
    ]
