# Generated by Django 4.2.7 on 2023-11-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_chat", "0002_remove_chatmessage_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="cost",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="tokens",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userdata",
            name="total_cost",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userdata",
            name="total_tokens",
            field=models.FloatField(default=0),
        ),
    ]
