# Generated by Django 4.2.10 on 2024-02-13 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("llm_chat", "0003_chatmessage_cost_chatmessage_tokens_and_more"),
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="llm_chat.userdata",
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
